### ISSUE TITLE
Certain characters copied as HTML entities

### ISSUE THREAD

**Issue by arvola** [znicholasbrown/vuepress-plugin-code-copy#1]
When copying code blocks, certain special HTML characters get copied as encoded entities.

For example, given the following code block:

```bash
echo "% & $ ? <" > less
```

The code copied to clipboard will actually be:

```
echo "% &amp; $ ? &lt;" &gt; less
```

I've fixed this by using innerText instead of innerHTML:

https://github.com/znicholasbrown/vuepress-plugin-code-copy/compare/master...arvola:master

**Comment by znicholasbrown** [comment]
Excellent addition @arvola! Would you mind opening a PR so I can test it and release?

**Comment by znicholasbrown** [comment]
Resolved by #2
