### ISSUE TITLE
TypeError: Cannot read property 'writeText' of undefined

### ISSUE THREAD

**Issue by coder163** [znicholasbrown/vuepress-plugin-code-copy#4]
TypeError: Cannot read property 'writeText' of undefined
在编译成HTML部署在站点之后提示上面的错误，在本地执行时一切正常，求教大神解决方法

项目的依赖如下：

 "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-rc.1",
    "leancloud-storage": "^3.15.0",
    "vuepress": "^1.0.0-rc.1",
    "vuepress-plugin-baidu-autopush": "^1.0.1"
  },
  "dependencies": {
    "valine": "^1.3.10",
    "vuepress-plugin-code-copy": "^1.0.4",
    "vuepress-plugin-copyright": "^1.0.2"
  }

**Comment by znicholasbrown** [comment]
谢谢@ coder163！ 我将对此问题进行调查并与您联系。 也可以随意进行PR!

**Comment by LanceZhu** [comment]
> TypeError: Cannot read property 'writeText' of undefined
> 在编译成HTML部署在站点之后提示上面的错误，在本地执行时一切正常，求教大神解决方法
> 
> 项目的依赖如下：
> 
> "devDependencies": {
> "@vuepress/plugin-back-to-top": "^1.0.0-rc.1",
> "leancloud-storage": "^3.15.0",
> "vuepress": "^1.0.0-rc.1",
> "vuepress-plugin-baidu-autopush": "^1.0.1"
> },
> "dependencies": {
> "valine": "^1.3.10",
> "vuepress-plugin-code-copy": "^1.0.4",
> "vuepress-plugin-copyright": "^1.0.2"
> }

`navigator.clipboard.writeText` may not compatible with your browser. See Browser compatibility in [Browser compatibility - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

**Comment by znicholasbrown** [comment]
This should resolve this: https://github.com/znicholasbrown/vuepress-plugin-code-copy/pull/8
