### ISSUE TITLE
Not works on iPhone

### ISSUE THREAD

**Issue by Grawl** [znicholasbrown/vuepress-plugin-code-copy#5]
Maybe just hide this button for MobileSafari?

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

https://stackoverflow.com/questions/34045777/copy-to-clipboard-using-javascript-in-ios

**Comment by znicholasbrown** [comment]
Hm good point - is there a way we could make this work on mobile safari? I can look into it sometime this week

**Comment by Grawl** [comment]
I think StackOverflow is good starting point to debug this

**Comment by znicholasbrown** [comment]
Should be resolved now @Grawl (as of https://github.com/znicholasbrown/vuepress-plugin-code-copy/pull/8) - let me know if you're still seeing issues
