### ISSUE TITLE
Ability to change implementation，This requires a secure origin。

### ISSUE THREAD

**Issue by hieastz** [znicholasbrown/vuepress-plugin-code-copy#7]
TypeError: Cannot read property 'writeText' of undefined is because navigator.clipboard is undefined。

The reason navigator.clipboard is undefined is requires a secure origin。
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

[docsify-copy-code](https://github.com/jperasmus/docsify-copy-code) for reference, it supports sources that are not secure。

**Comment by znicholasbrown** [comment]
Hi @haydonchou, I just opened a PR (https://github.com/znicholasbrown/vuepress-plugin-code-copy/pull/8) that should take care of this!
